# Generated by Django 3.0.3 on 2020-02-21 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstsiteapp', '0002_auto_20200221_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='text',
        ),
        migrations.RemoveField(
            model_name='book',
            name='update',
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstsiteapp.Year'),
            preserve_default=False,
        ),
    ]
