# Generated by Django 3.0.3 on 2020-02-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstsiteapp', '0008_auto_20200221_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=20),
        ),
    ]
