# Generated by Django 3.0.3 on 2020-02-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstsiteapp', '0009_auto_20200221_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
