# Generated by Django 3.0.3 on 2020-02-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstsiteapp', '0010_auto_20200221_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ('-name',)},
        ),
    ]
